[package]
name = "leetcode-in-rust"
version = "0.1.0"
authors = ["Zehua Zou <41586196+HuaHuaY@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
